//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAlojamentoLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamento()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public string num { get; set; }
        public string tipo { get; set; }
        public string lotação { get; set; }
        public decimal custoNoite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
