//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAlojamentoLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateReserva { get; set; }
        public Nullable<System.DateTime> dateCheckIn { get; set; }
        public Nullable<System.DateTime> dateCheckOut { get; set; }
        public Nullable<int> idAlojamento { get; set; }
        public Nullable<decimal> custo { get; set; }
        public Nullable<int> idCustomer { get; set; }
    
        public virtual Alojamento Alojamento { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
